version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  node: circleci/node@1.1

executors:
  cypress-large:
    docker:
      - image: "cypress/base:14.17.0"
    resource_class: large
    environment:
      NODE_OPTIONS: --max_old_space_size=4096

references:
  default_config: &default_config
    docker:
      - image: node:16-slim

  test: &test
    <<: *default_config
    steps:
      - checkout
      - run:
          name: test
          command: |
            set -eo pipefail
            npm install
            npm run ts:lint

  publish: &publish
    <<: *default_config
    steps:
      - checkout
      - run:
          name: publish
          command: |
            set -eo pipefail
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm install
            npm run build
            cp ./package.json dist
            cp ./README.md dist
            cd dist
            npm publish --access public

jobs:
  test:
    <<: *test
  publish:
    <<: *publish
workflows:
  version: 2.1
  test-and-publish:
    jobs:
      - test:
          context: bavard
          filters:
            tags:
              only: /.*/
      - cypress/run:
          timeout: 15m
          executor: cypress-large
          context: bavard
          record: true
          install-command: |
            set -eo pipefail
            npm install -g npm
            npm install
          requires:
            - test
          start: npm run ci:start:test
          wait-on: "http://localhost:8080"
          filters:
            tags:
              only: /^$/
      - hold:
          context: bavard-prod
          type: approval
          filters:
            branches:
              only: main
          requires:
            - test
      - publish:
          context: bavard
          filters:
            branches:
              only: main
          requires:
            - hold
